name: xml_styled_text
description: Flutter text styling using XML tags.
version: 0.0.2
publish_to: 'none'

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  xml: ^6.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

dependency_overrides:
  meta: ^1.17.0

flutter:
